-- 003_store_payment_bootstrap.sql
-- Compatibility bootstrap for environments that seeded catalog tables
-- but do not yet have Stripe/payment columns and purchase tables.

begin;

alter table public.course_packs
  add column if not exists stripe_price_id text,
  add column if not exists stripe_product_id text;

create table if not exists public.user_purchases (
  id bigint generated by default as identity primary key,
  user_id text not null,
  course_pack_id text not null,
  stripe_checkout_session_id text,
  stripe_payment_intent_id text,
  amount_paid numeric(10, 2),
  currency text default 'usd',
  status text default 'pending' check (status in ('pending', 'completed', 'failed', 'refunded')),
  purchased_at timestamptz default now(),
  unique (user_id, course_pack_id)
);

create table if not exists public.user_subscriptions (
  id bigint generated by default as identity primary key,
  user_id text not null,
  plan_type text check (plan_type in ('all_access_monthly', 'all_access_annual')),
  stripe_subscription_id text unique,
  status text default 'active',
  current_period_start timestamptz,
  current_period_end timestamptz,
  created_at timestamptz default now()
);

create index if not exists idx_user_purchases_user_status_purchased_at
  on public.user_purchases (user_id, status, purchased_at desc);

create index if not exists idx_user_subscriptions_user_status_period_end
  on public.user_subscriptions (user_id, status, current_period_end);

commit;
