-- 20261006000100_seed_catalog.sql
-- Catalog seed: 4 academic levels, 14 degree plans, 56 course packs (14 x 4).
--
-- Ported from the legacy backend/migrations/001_seed_academic_data.sql and
-- 002_seed_course_packs.sql (now docs/archive/legacy-migrations/) to the
-- bigint-identity schema of 20261006000000_baseline.sql. Ids are generated by the
-- identity columns; backend/scripts/relink_stripe_catalog.py (D4) maps packs to the
-- existing Stripe Test objects by slug, not by id.
--
-- Idempotent: every statement upserts on its natural key and NEVER touches
-- course_packs.stripe_price_id / stripe_product_id, which the relink script owns.
-- Re-running refreshes names, copy, prices and is_active only.
--
-- Feature copy is deliberately truthful (plan §4-19 / D7). A pack today delivers
-- exactly two things: AI mentor context tuned to its degree plan and level, and
-- lifetime access for a one-time purchase. It does NOT ship study guides, practice
-- questions or vocabulary sets (content_items is never served), so none are
-- promised here. Prices are unchanged from the legacy seed.

begin;

-- ----------------------------------------------------------------------------
-- Academic levels
-- ----------------------------------------------------------------------------
insert into public.academic_levels (name, slug, display_order, description)
values
  ('Freshman', 'freshman', 1, 'Foundational vocabulary, intro concepts, and core study habits.'),
  ('Sophomore', 'sophomore', 2, 'Intermediate theory, applied methods, and research basics.'),
  ('Junior', 'junior', 3, 'Advanced specialization with applied analysis and case-based learning.'),
  ('Senior', 'senior', 4, 'Capstone synthesis, professional preparation, and licensure readiness.')
on conflict (slug) do update
set
  name = excluded.name,
  display_order = excluded.display_order,
  description = excluded.description;

-- ----------------------------------------------------------------------------
-- Degree plans
-- ----------------------------------------------------------------------------
insert into public.degree_plans (name, slug, category, description, icon_name, is_active)
values
  ('Nursing', 'nursing', 'healthcare', 'Patient care, pharmacology, and evidence-based nursing practice.', 'stethoscope', true),
  ('Respiratory Therapy', 'respiratory-therapy', 'healthcare', 'Airway management, ventilator support, and cardiopulmonary care.', 'lungs', true),
  ('Radiology / X-Ray', 'radiology', 'healthcare', 'Diagnostic imaging principles, safety, and interpretation workflows.', 'scan-line', true),
  ('Psychology', 'psychology', 'social_sciences', 'Behavior, cognition, research methods, and applied psychological science.', 'brain', true),
  ('Criminal Justice', 'criminal-justice', 'social_sciences', 'Law enforcement systems, legal process, and community justice.', 'shield', true),
  ('Sociology', 'sociology', 'social_sciences', 'Social structures, institutions, and research-based social analysis.', 'users', true),
  ('Biochemistry', 'biochemistry', 'stem', 'Molecular biology, metabolism, and lab-driven scientific reasoning.', 'flask-conical', true),
  ('Computer Science', 'computer-science', 'stem', 'Programming, data structures, algorithms, and software engineering foundations.', 'cpu', true),
  ('Engineering', 'engineering', 'stem', 'Applied mathematics, design systems, and technical problem solving.', 'wrench', true),
  ('Business Administration', 'business-admin', 'business', 'Management, operations, and strategic business decision-making.', 'briefcase', true),
  ('Accounting', 'accounting', 'business', 'Financial statements, managerial accounting, and compliance principles.', 'calculator', true),
  ('Marketing', 'marketing', 'business', 'Brand strategy, market research, and campaign analytics.', 'megaphone', true),
  ('Early Childhood Education', 'early-childhood', 'education', 'Child development, classroom practice, and family-centered learning.', 'book-open', true),
  ('Special Education', 'special-education', 'education', 'Individualized support planning, inclusive instruction, and intervention methods.', 'sparkles', true)
on conflict (slug) do update
set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  icon_name = excluded.icon_name,
  is_active = excluded.is_active;

-- ----------------------------------------------------------------------------
-- Course packs: every active degree plan x every academic level
-- ----------------------------------------------------------------------------
with level_pricing as (
  select
    al.id as academic_level_id,
    al.slug as academic_level_slug,
    al.name as academic_level_name,
    case al.slug
      when 'freshman' then 19.99::numeric(10, 2)
      when 'sophomore' then 24.99::numeric(10, 2)
      when 'junior' then 29.99::numeric(10, 2)
      when 'senior' then 34.99::numeric(10, 2)
      else 24.99::numeric(10, 2)
    end as level_price
  from public.academic_levels al
  where al.slug in ('freshman', 'sophomore', 'junior', 'senior')
),
pack_matrix as (
  select
    dp.id as degree_plan_id,
    dp.name as degree_plan_name,
    dp.slug as degree_plan_slug,
    lp.academic_level_id,
    lp.academic_level_slug,
    lp.academic_level_name,
    lp.level_price
  from public.degree_plans dp
  cross join level_pricing lp
  where dp.is_active = true
)
insert into public.course_packs (
  degree_plan_id,
  academic_level_id,
  name,
  slug,
  description,
  price,
  features,
  is_active
)
select
  pm.degree_plan_id,
  pm.academic_level_id,
  pm.degree_plan_name || ' - ' || pm.academic_level_name || ' Pack' as name,
  pm.degree_plan_slug || '-' || pm.academic_level_slug as slug,
  'Tunes the AI mentor to ' || pm.degree_plan_name || ' at the ' || pm.academic_level_name
    || ' level. One-time purchase with lifetime access.' as description,
  pm.level_price,
  jsonb_build_array(
    'AI mentor context tuned to ' || pm.degree_plan_name || ' (' || pm.academic_level_name || ')',
    'Lifetime access for one-time purchase'
  ) as features,
  true
from pack_matrix pm
on conflict (degree_plan_id, academic_level_id) do update
set
  name = excluded.name,
  slug = excluded.slug,
  description = excluded.description,
  price = excluded.price,
  features = excluded.features,
  is_active = excluded.is_active;
  -- stripe_price_id / stripe_product_id intentionally untouched.

commit;
